### DISCUSSION TITLE
Build file '.pub-cache/hosted/pub.dev/audioplayers_android-3.0.1/android/build.gradle' line: 31

### DISCUSSION THREAD

**Discussion by nabtron** [bluefireteam/audioplayers#1589] [General]
I am getting this error when running `flutter run`

```
FAILURE: Build failed with an exception.

* Where:
Build file '/Users/one/.pub-cache/hosted/pub.dev/audioplayers_android-3.0.1/android/build.gradle' line: 31

* What went wrong:
A problem occurred evaluating project ':audioplayers_android'.
> No signature of method: build_a63qjm1kfe3oz0etex305ie55.android() is applicable for argument types: (build_a63qjm1kfe3oz0etex305ie55$_run_closure2) values: [build_a63qjm1kfe3oz0etex305ie55$_run_closure2@16440ebf]
```

The `flutter run --verbose` shows this output:

```
 > Configure project :audioplayers_android
[        ] Evaluating project ':audioplayers_android' using build file '/Users/one/.pub-cache/hosted/pub.dev/audioplayers_android-3.0.1/android/build.gradle'.
[        ] Creating configuration androidTestUtil
[        ] FAILURE: Build failed with an exception.
[   +1 ms] * Where:
[        ] Build file '/Users/one/.pub-cache/hosted/pub.dev/audioplayers_android-3.0.1/android/build.gradle' line: 31
[        ] * What went wrong:
[        ] A problem occurred evaluating project ':audioplayers_android'.
[        ] > No signature of method: build_a63qjm1kfe3oz0etex305ie55.android() is applicable for argument types: (build_a63qjm1kfe3oz0etex305ie55$_run_closure2) values: [build_a63qjm1kfe3oz0etex305ie55$_run_closure2@5a21456d]
[        ] * Try:
[        ] Run with --debug option to get more log output. Run with --scan to get full insights.
[        ] * Exception is:
[        ] org.gradle.api.GradleScriptException: A problem occurred evaluating project ':audioplayers_android'.
[        ]      at org.gradle.groovy.scripts.internal.DefaultScriptRunnerFactory$ScriptRunnerImpl.run(DefaultScriptRunnerFactory.java:93)
[        ]      at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.lambda$apply$0(DefaultScriptPluginFactory.java:133)
[        ]      at org.gradle.configuration.ProjectScriptTarget.addConfiguration(ProjectScriptTarget.java:77)
[        ]      at org.gradle.configuration.DefaultScriptPluginFactory$ScriptPluginImpl.apply(DefaultScriptPluginFactory.java:136)
[        ]      at org.gradle.configuration.BuildOperationScriptPlugin$1.run(BuildOperationScriptPlugin.java:65)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:29)
[        ]      at org.gradle.internal.operations.DefaultBuildOperationRunner$1.execute(DefaultBuildOperationRunner.java:26)
.
.
.
.
```

Please guide how to proceed.

My pubspec.yaml file is:

```
name: pavlov_alarm
description: A new Flutter application.

publish_to: 'none' # Remove this line if you wish to publish to pub.dev

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  flutter:
    sdk: flutter

  cupertino_icons: ^1.0.3
  intl: ^0.18.0
  # android_alarm_manager: ^2.0.2
  android_alarm_manager_plus: ^2.1.2
  shared_preferences: ^2.0.7
  url_launcher: ^6.0.10
  flutter_local_notifications: ^13.0.0
  flutter_local_notifications_platform_interface: ^6.0.0
  timezone: ^0.9.1
  rxdart: ^0.27.2
  flutter_native_timezone: ^2.0.0
  # flutter_datetime_picker: ^1.5.1
  # vibration: ^1.7.4-nullsafety.0
  vibration: ^1.7.6
  audioplayers: ^4.0.1
  # audioplayers: ^3.0.1
  # audioplayers: ^0.20.1
  future_progress_dialog: ^0.2.0
  flutter_credit_card: ^3.0.6
  flutter_stripe: ^9.0.0
  http: ^0.13.3
  hive: ^2.0.4
  hive_flutter: ^1.1.0
  path_provider: ^2.0.3
  flutter_picker: ^2.0.2
  hive_generator: ^2.0.0
  # hive_generator: ^1.1.1
  build_runner: ^2.1.2

dev_dependencies:
  flutter_test:
    sdk: flutter

flutter:
  uses-material-design: true
  fonts:
    - family: JosefinSans
      fonts:
        - asset: assets/fonts/JosefinSans-Regular.ttf
  assets:
    - assets/sound1.wav

```

Thanks
