### ISSUE TITLE
[^1.0.0-rc.4] Occasional 'IllegalStateException' when loading audio from device source on Android

### ISSUE THREAD

**Issue by mzkai** [bluefireteam/audioplayers#1150]
I occasionally get the error below when running the following piece of code. Most of the time this works fine, but around 5% of the time the error will come up. I have only tested this on Android, but might be the same on iOS.

Code executed:
```
File audioFile = await <getting-audio-file-from-internet-and-save-to-device>
await _audioPlayer.setSource(DeviceFileSource(audioFile.path));
_audioPlayer.setVolume(1);
_audioPlayer.resume();
```

Error received:
```
java.lang.IllegalStateException: null
    at android.media.MediaPlayer.isPlaying(MediaPlayer.java)
    at xyz.luan.audioplayers.player.MediaPlayerPlayer.isActuallyPlaying(MediaPlayerPlayer.kt:35)
    at xyz.luan.audioplayers.player.WrappedPlayer.isActuallyPlaying(WrappedPlayer.kt:144)
    at xyz.luan.audioplayers.AudioplayersPlugin$UpdateCallback.run(AudioplayersPlugin.kt:209)
    at android.os.Handler.handleCallback(Handler.java:883)
    at android.os.Handler.dispatchMessage(Handler.java:100)
    at android.os.Looper.loop(Looper.java:230)
    at android.app.ActivityThread.main(ActivityThread.java:7876)
    at java.lang.reflect.Method.invoke(Method.java)
    at com.android.internal.os.RuntimeInit$MethodAndArgsCaller.run(RuntimeInit.java:526)
    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:1034)
```

Version information:
```
flutter: 3.0.1
audioplayers: ^1.0.0-rc.4
```

**Comment by JMS55** [comment]
I can confirm that I'm seeing something similar on android. It seems to happen very consistently every other time I try to play a url from the internet. The first play works fine, the second crashes, the third works fine. Code is here https://github.com/JMS55/trackstar.
```
D/AudioPlayers( 3312): Unexpected error!
D/AudioPlayers( 3312): java.lang.IllegalStateException
D/AudioPlayers( 3312): 	at android.media.MediaPlayer.nativeSetDataSource(Native Method)
D/AudioPlayers( 3312): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1204)
D/AudioPlayers( 3312): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1191)
D/AudioPlayers( 3312): 	at android.media.MediaPlayer.setDataSource(MediaPlayer.java:1156)
D/AudioPlayers( 3312): 	at xyz.luan.audioplayers.source.UrlSource.setForMediaPlayer(UrlSource.kt:16)
D/AudioPlayers( 3312): 	at xyz.luan.audioplayers.player.MediaPlayerPlayer.setSource(MediaPlayerPlayer.kt:51)
D/AudioPlayers( 3312): 	at xyz.luan.audioplayers.player.WrappedPlayer.setSource(WrappedPlayer.kt:29)
D/AudioPlayers( 3312): 	at xyz.luan.audioplayers.AudioplayersPlugin.handler(AudioplayersPlugin.kt:87)
D/AudioPlayers( 3312): 	at xyz.luan.audioplayers.AudioplayersPlugin.access$handler(AudioplayersPlugin.kt:23)
2
D/AudioPlayers( 3312): 	at xyz.luan.audioplayers.AudioplayersPlugin$onAttachedToEngine$1$1.invoke(AudioplayersPlugin.kt:39)
D/AudioPlayers( 3312): 	at xyz.luan.audioplayers.AudioplayersPlugin$safeCall$1.invokeSuspend(AudioplayersPlugin.kt:58)
D/AudioPlayers( 3312): 	at kotlin.coroutines.jvm.internal.BaseContinuationImpl.resumeWith(ContinuationImpl.kt:33)
D/AudioPlayers( 3312): 	at kotlinx.coroutines.DispatchedTask.run(DispatchedTask.kt:106)
D/AudioPlayers( 3312): 	at kotlinx.coroutines.internal.LimitedDispatcher.run(LimitedDispatcher.kt:39)
```

**Comment by sujindra-maharjan** [comment]
Is this error fixed?

**Comment by yakubmoris** [comment]
Any update on this issue, We are also facing same issue in android if we try to play same file several time one after another.

**Comment by Gustl22** [comment]
Seems like the Android `MediaPlayer` is still in another state while setting the source.

We added a bunch of fixes to the main branch, can you test your apps again with:
```
dependency_overrides: 
  audioplayers:
    git: 
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers'
  audioplayers_platform_interface:
    git: 
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_platform_interface'
  audioplayers_android:
    git: 
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_android'
```
