### ISSUE TITLE
In audioPlayer.onPlayerComplete event listener, player.state is still playing state

### ISSUE THREAD

**Issue by jzz567** [bluefireteam/audioplayers#1242]
## Checklist
- [x] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [x] I made sure that the issue I am raising doesn't already exist

## Current bug behaviour

When an audio file play finished, audioPlayer.onPlayerComplete is triggered, but in this  event listener, player state is still in playing state.
Also if I have a button, user can click it to get the audio player state, after audio file play finished, user click button, the audio player.state is also in playing state.

## Expected behaviour

In audioPlayer.onPlayerComplete listener, player.state is complete
After audio file play finished, player.state is complete

## Steps to reproduce

1. Add onPlayerComplete listener
2. print player.state in onPlayerComplete listener
3. print output playing

<details>
<summary>
</summary>

```dart
audioPlayer.onPlayerComplete.listen(() {
print(audioPlayer.state==PlayerState.playing);// true
}
<Button onPress()=>{
print(audioPlayer.state==PlayerState.playing);}>click</Button>
// after audio file play finished, button click will output true
```

</details>

## Environment information

* audioplayers version: 1.0.1

Platform: 
* OS name and version: android 10
* Device: android emulator
* build mode: `debug`

* error peculiarities (optional):

**Comment by Nico3652** [comment]
Same problem detected for my app. Seems to be a regression because I used the plugin since start of 2022 and It was working perfectly. 

When the the audio file is playing and auto complete/end the playerState is not triggering ' completed ' state. Same for 'stopped'.
Whereas 'pause' is still working.

thanks!

**Comment by itsJoKr** [comment]
I have the same issue. I've updated to ` audioplayers: ^1.0.1` and the state is always `playing` even though it finished playing. In `0.20.1` it worked for me.

**Comment by Tom3652** [comment]
Seeing the same behavior as mentioned above in my app with the `audioplayers: ^1.0.1`

**Comment by itsJoKr** [comment]
Hey, guys. I might have a fix, it's here: https://github.com/bluefireteam/audioplayers/pull/1257

And you can test it before release. If you do, please tell me if it worked for you: 

```
  audioplayers:
    git:
      url: https://github.com/itsJoKr/audioplayers.git
      path: packages/audioplayers
      ref: 0afb518e38f23717d0628ab89a72c08aaf6ce097
```

**Comment by Tom3652** [comment]
Hey @itsJoKr , thanks for working on it ! 
I have tried your version and i see the same behavior unfortunately, it doesn't call any other event than `PlayerState.playing` :/

**Comment by itsJoKr** [comment]
@Tom3652 Ah, I think I have one bug that happens in your use case, can you try this one:

```
  audioplayers:
    git:
      url: https://github.com/itsJoKr/audioplayers.git
      path: packages/audioplayers
      ref: f82378f476dcf5a597ef02ba1ed7294eb3a65f7d
```
