### ISSUE TITLE
AudioPlayers 5.2.0 failed to play firebase storage url on Web

### ISSUE THREAD

**Issue by alanguodev** [bluefireteam/audioplayers#1700]
### Checklist

- [X] I read the [troubleshooting guide](https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md) before raising this issue
- [X] I made sure that the issue I am raising doesn't already exist

### Current bug behaviour

AudioPlayers 5.10.0 
firebase storage url plays well in Android but fails to play in Flutter web. Error:
AudioPlayers Exception: AudioPlayerException(
	UrlSource(url: https://firebasestorage.googleapis.com/v0/b/paddle-quiz-app.appspot.com/o/tts%2Fen-US%2Fgoogle%2Fneural2%2Fdefault%2Fbe70ef344b7f3df2216421a36467b9a3.mp3?alt=media&token=f08af17f-7ddb-44ce-8ccf-cb105ed528f6),
	PlatformException(WebAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, MediaError: MEDIA_ELEMENT_ERROR: Format error (Code: 4), null)
Error: PlatformException(WebAudioError, Failed to set source. For troubleshooting, see https://github.com/bluefireteam/audioplayers/blob/main/troubleshooting.md, MediaError: MEDIA_ELEMENT_ERROR: Format error (Code: 4), null)

### Expected behaviour

Play the same as in Android.

### Steps to reproduce

1. Execute `flutter run` on the code sample 
2. ... 
3. ... 

### Code sample

<details>
<summary>Code sample</summary>

```dart
void main() {
}
```

</details>

### Affected platforms

web

### AudioPlayers Version

5.10.0

### Logs

```
my relevant logs
```

<details>
  <summary>Full Logs</summary>

  

  ```
  my full logs or a link to a gist
  ```

  Flutter doctor:
  ```
  Output of: flutter doctor -v
  ```
</details>

### Working on PR

no way

**Comment by Shubham-VE** [comment]
For me, this was working fine earlier but then it began to give this error. I am not sure if this is due to Flutter(v3.1.10 to v3.13.7 for me) upgrade or the package version upgrade as I noticied this error a bit late.

**Comment by Shubham-VE** [comment]
Adding this resolved the issue for me:
```
dependency_overrides:
  audioplayers:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers'
  audioplayers_platform_interface:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_platform_interface'
  audioplayers_web:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_web'
  audioplayers_linux:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_linux'
  audioplayers_android:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_android'
  audioplayers_darwin:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_darwin'
  audioplayers_windows:
    git:
      url: https://github.com/bluefireteam/audioplayers.git
      path: 'packages/audioplayers_windows'
```
